namespace: teva-vayusense
replicas:
  tevaMonitor: 2
  tevaIc: 3

apps:
  name: tevamonitor
  version: 0.1.0

images:
  ic:
    repository: vayusense/ic
    tag: latest
    pullPolicy: IfNotPresent
  monitor:
    repository: vayusense/monitor
    tag: latest
    pullPolicy: IfNotPresent

service:
  monitor:
    type: ClusterIP
    port: 8761
  ic:
    type: NodePort
    port: 8080

spring:
  monitor:
    config:
      serverPort: "8761"
      springSecurityUsername: admin
      mailHost: smtp.gmail.com
      mailPort: "587"
      mailUsername: danielshjobs@gmail.com
      notifyMailTo: daniel@vayusense.com
      baseUrl: http://ic-service:8080/api/v1
    secret:
      springSecurityPassword: admin
      mailPassword: rnquofhmtdswngbp
  ic:
    config:
      serverPort: "8080"
      mongoHost: cluster0-8mm27.mongodb.net/biotec?retryWrites=true&w=majority
      mongoDatabase: biotec
      mongoUserName: danielvayu
      rabbitMQAddresses: amqps://tfqajxis:sEYFg6OkFrzKZs93BddQtI3MXf04_dZQ@kangaroo.rmq.cloudamqp.com/tfqajxis
      app1ExchangeName: stateteva-exchange
      app1QueueName: stateteva
      app1RoutingKey: stateteva-routing-key
      app2ExchangeName: logteva-exchange
      app2QueueName: logteva
      app2RoutingKey: logteva-routing-key
      app3ExchangeName: unitteva-exchange
      app3QueueName: unitteva
      app3RoutingKey: unitteva-routing-key
      springBootAdminUrl: http://tevamonitor-service:8761
      springBootAdminUsername: admin
      springAdminClientuserUserName: client
      infoApiRestUrl: http://ic-service:8080/swagger-ui.html#
    secret:
      mongodbPassword: admin
      springBootAdminPassword: admin
      springAdminClientuserPassword: clientPassword

resources:
  limits:
    monitor:
      cpu: 500m
      memory: 512Mi
    ic:
      cpu: 1000m
      memory: 1024Mi
  requests:
    monitor:
      cpu: 200m
      memory: 256Mi
    ic:
      cpu: 500m
      memory: 512Mi

tolerations: []

affinity: {}
