apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $val := .Values.spring.ic.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}