apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.apps.monitor.name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $val := .Values.spring.monitor.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}