apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.apps.name }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: gce
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: {{ .Chart.Name }}-service
              servicePort: 8080
          - path: /monitor
            backend:
              serviceName: {{ .Values.apps.monitor.name }}-service
              servicePort: 8761