apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: {{ .Chart.Name }}-service
              servicePort: 8080
          - path: /monitor
            backend:
              serviceName: {{ .Values.apps.name }}-service
              servicePort: 8761