apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.spring.ic.secret }}
  {{ $key }}: {{ $val }}
  {{- end }}