apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.apps.monitor.name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.spring.monitor.secret }}
  {{ $key }}: {{ $val }}
  {{- end }}