apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apps.name }}-service
  namespace: {{ .Values.namespace }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    {{ .Values.apps.name }}-service
spec:
  type: {{ .Values.service.monitor.type }}
  ports:
    - name: "http"
      port: {{ .Values.service.monitor.port }}
      targetPort: {{ .Values.service.monitor.port }}
  selector:
    app: {{ .Values.apps.name }}
    release: {{ .Values.apps.name }}-{{ .Values.apps.version | replace "+" "_" }}
