apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.namespace }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    {{ .Chart.Name }}-service
spec:
  type: {{ .Values.service.ic.type }}
  ports:
    - name: "http"
      port: {{ .Values.service.ic.port }}
      targetPort: {{ .Values.service.ic.port }}
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
